### ISSUE TITLE
Is an arbitrary time parser desirable?

### ISSUE THREAD

**Issue by jcguu95** [dlowe-net/local-time#108]
Formatting time is simpler than parsing time. Currently, we can parse time with respect to a few formats. I am thinking of implementing a time parser for elisp, and think it will also be useful to make a clone for `local-time`. Please let me know if that's going go be desirable for this project.

**Comment by dlowe-net** [comment]
I'm not entirely sure what this issue is about. If you want a flexible time parser that works with local-time, the [chronicity](https://github.com/chaitanyagupta/chronicity) library has you covered. If you want to implement local-time in elisp, feel free. It's not going to be part of this project, however.

Closing due to lack of actionable items.
